"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-$du6=b@-a^c&sg#hj$ffnx+pyfquths_*9kvzx&gn^q$4-hdut')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ["*", "127.0.0.1", "192.168.1.173", "0.0.0.0", "integral-logically-gator.ngrok-free.app"]
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Autoriser les requêtes POST/PUT depuis ngrok et Render (indispensable pour l'auth)
CSRF_TRUSTED_ORIGINS = ["https://integral-logically-gator.ngrok-free.app"]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# Informer Django que le tunnel ngrok/Render gère le HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Faire confiance à l'en-tête Host envoyé par le proxy (ngrok/Render)
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    
    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
   
    
    'allauth',
    'allauth.account',
      'django.contrib.sites', 
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Google OAuth
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'drf_spectacular',
    
    
    # Local apps
    'utilisateur',
    'catalogue',
    'laboratoire',
    'orders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Devrait être le plus haut possible
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir les fichiers statiques en prod
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Requis par allauth
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# Backends d'authentification
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend Django standard
    'allauth.account.auth_backends.AuthenticationBackend',  # Backend allauth
]


WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#model utilise pour lauthentification
AUTH_USER_MODEL = 'utilisateur.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}





# Site ID pour django-allauth
SITE_ID = 3

# ============================================================
# CONFIGURATION DJANGO-ALLAUTH
# ============================================================
# Authentification par email ou téléphone
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Base sur email
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # L'utilisateur doit vérifier son email avant validation
ACCOUNT_USERNAME_REQUIRED = False  # Le username n'est pas obligatoire pour l'utilisateur
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_CHANGE_EMAIL = True  # Remplace user.email uniquement après confirmation allauth

SOCIALACCOUNT_AUTO_SIGNUP = True  # Création automatique du compte sans formulaire
SOCIALACCOUNT_LOGIN_ON_GET = True # Évite une étape de confirmation inutile
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# URL du Frontend (Variable d'environnement ou localhost par défaut)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Adaptateur personnalisé pour gérer la redirection des emails vers le Frontend
ACCOUNT_ADAPTER = 'utilisateur.adapters.CustomAccountAdapter'
# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login_ip': '20/15min',
        'login_credential': '5/15min',
        'register_ip': '3/hour',
        'register_email': '5/day',
        'resend_email_short': '1/2min',
        'resend_email_daily': '5/day',
        'password_reset_ip': '10/hour',
        'password_reset_email': '3/hour',
        'change_email': '3/hour',
        'ia_anon': '5/hour',
        'ia_user': '30/day',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ============================================================
# DJ-REST-AUTH (utilise JWT)
# ============================================================
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'access-token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh-token',
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SECURE': True,
    'JWT_AUTH_SAMESITE': 'None',
    'LOGIN_SERIALIZER': 'utilisateur.serializers.EmailOrTelephoneLoginSerializer',
    'REGISTER_SERIALIZER': 'utilisateur.serializers.CustomRegisterSerializer',
    'PASSWORD_CHANGE_SERIALIZER': 'utilisateur.serializers.CustomPasswordChangeSerializer',
    'PASSWORD_RESET_USE_SITES_DOMAIN': False,
    'PASSWORD_RESET_CONFIRM_URL': FRONTEND_URL + '/auth/reset-password-confirm/{uid}/{token}/',
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'handougregoire@gmail.com' # ← Mets ton vrai mail ici
EMAIL_HOST_PASSWORD = 'qvfs vdfn uyny xjqw'
# Ton mot de passe d'application est parfait
DEFAULT_FROM_EMAIL = 'Accessoire Exclusif <handougregoire@gmail.com>'

# Configuration des cookies pour le Cross-Site (Frontend distant)
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ["https://integral-logically-gator.ngrok-free.app", "http://172.20.10.5:3000"]





# ============================================================
# DRF SPECTACULAR (Swagger / OpenAPI)
# ============================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'Accessoire Exclusif API',
    'DESCRIPTION': 'API pour la plateforme de parfums et accessoires exclusifs',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}




GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', 'AIzaSyCJWtJ0sHkr5vCRyKxMd4hvzyCN5rfTkK8')

# Configuration Monetbil (Virement/Payout)
MONETBIL_SERVICE_KEY = os.getenv('MONETBIL_SERVICE_KEY', 'NhlyzHMYo961mQZ3uCQEUX2xUGUaFhUm')
MONETBIL_SERVICE_SECRET = os.getenv('MONETBIL_SERVICE_SECRET', 'uhvzMBmTvIHR2AYMZdZHeAid3G3SfFqos1fj6TXzkABOZ9e8BVLCjSUcZqLuPXkl')
MONETBIL_API_URL = os.getenv('MONETBIL_API_URL', 'https://api.monetbil.com/v1')

#gerer les images 
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============================================================
# CONFIGURATION CORS (Sécurité d'accès cross-origin)
# ============================================================
from corsheaders.defaults import default_headers

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://172.20.10.5:3000",
        "https://integral-logically-gator.ngrok-free.app",
    ]
CORS_ALLOW_CREDENTIALS = True  # Crucial pour autoriser le partage des cookies HttpOnly
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-client-type',
    'ngrok-skip-browser-warning',
]
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # Frontend Web
#     "http://127.0.0.1:3000",
# ]
