# Generated by Django 4.2.30 on 2026-05-28 14:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssencePersonnalisee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom donné par le client à son essence', max_length=200)),
                ('prix_par_ml_calcule', models.DecimalField(decimal_places=2, default=0, help_text='Prix calculé en fonction des ingrédients', max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Essence Personnalisée',
                'verbose_name_plural': 'Essences Personnalisées',
                'db_table': 'essence_personnalisee',
            },
        ),
        migrations.CreateModel(
            name='EssencePersonnaliseeLigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ml', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('prix_par_ml_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ligne', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': "Ligne d'essence personnalisée",
                'verbose_name_plural': "Lignes d'essences personnalisées",
                'db_table': 'essence_personnalisee_ligne',
            },
        ),
        migrations.CreateModel(
            name='ParfumPersonnalise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_essences', models.DecimalField(decimal_places=2, help_text='Somme calculée des prix des essences', max_digits=10)),
                ('prix_flacon_snapshot', models.DecimalField(decimal_places=2, help_text='Prix du flacon au moment de la création', max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, help_text='prix_essences + prix_flacon_snapshot', max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validé', 'Validé')], default='brouillon', max_length=30)),
                ('note_laboratoire', models.TextField(blank=True, help_text='Retour du labo en cas de refus')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parfum personnalisé',
                'verbose_name_plural': 'Parfums personnalisés',
                'db_table': 'parfum_personnalise',
            },
        ),
        migrations.CreateModel(
            name='ParfumPersonnaliseLigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ml', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('prix_par_ml_snapshot', models.DecimalField(decimal_places=2, help_text="Prix de l'essence au ml au moment de la création", max_digits=10)),
                ('prix_ligne', models.DecimalField(decimal_places=2, help_text='prix_par_ml_snapshot * quantite_ml', max_digits=10)),
                ('essence_catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_parfum', to='catalogue.essence')),
                ('essence_personnalisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_parfum', to='laboratoire.essencepersonnalisee')),
                ('parfum_personnalise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='laboratoire.parfumpersonnalise')),
            ],
            options={
                'verbose_name': 'Ligne de parfum personnalisé',
                'verbose_name_plural': 'Lignes de parfums personnalisés',
                'db_table': 'parfum_personnalise_ligne',
            },
        ),
    ]
