# Generated by Django 6.0.4 on 2026-04-30 12:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParfumPersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contenance_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prix_essences', models.DecimalField(decimal_places=2, help_text='Somme calculée des prix des essences', max_digits=10)),
                ('prix_flacon_snapshot', models.DecimalField(decimal_places=2, help_text='Prix du flacon au moment de la création', max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, help_text='prix_essences + prix_flacon_snapshot', max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validé', 'Validé')], default='brouillon', max_length=30)),
                ('note_laboratoire', models.TextField(blank=True, help_text='Retour du labo en cas de refus')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parfum personnalisé',
                'verbose_name_plural': 'Parfums personnalisés',
                'db_table': 'parfum_personnalise',
            },
        ),
        migrations.CreateModel(
            name='ParfumPersonnaliseLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ml', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('prix_par_ml_snapshot', models.DecimalField(decimal_places=2, help_text="Prix de l'essence au moment de la création", max_digits=10)),
                ('prix_ligne', models.DecimalField(decimal_places=2, help_text='(prix_par_10ml_snapshot * quantite_ml) / 10', max_digits=10)),
            ],
            options={
                'verbose_name': 'Ligne de parfum personnalisé',
                'verbose_name_plural': 'Lignes de parfums personnalisés',
                'db_table': 'parfum_personnalise_ligne',
            },
        ),
    ]
