# Generated by Django 4.2.30 on 2026-05-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('laboratoire', '0001_initial'),
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parfumpersonnalise',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parfums_personnalises', to='utilisateur.client'),
        ),
        migrations.AddField(
            model_name='parfumpersonnalise',
            name='flacon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parfums_personnalises', to='catalogue.flacon'),
        ),
        migrations.AddField(
            model_name='essencepersonnaliseeligne',
            name='essence_personnalisee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='laboratoire.essencepersonnalisee'),
        ),
        migrations.AddField(
            model_name='essencepersonnaliseeligne',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='catalogue.ingredient'),
        ),
        migrations.AddField(
            model_name='essencepersonnalisee',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essences_personnalisees', to='utilisateur.client'),
        ),
        migrations.AlterUniqueTogether(
            name='essencepersonnaliseeligne',
            unique_together={('essence_personnalisee', 'ingredient')},
        ),
    ]
