# Generated by Django 6.0.4 on 2026-04-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('laboratoire', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parfumpersonnalise',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parfums_personnalises', to='utilisateur.client'),
        ),
        migrations.AddField(
            model_name='parfumpersonnalise',
            name='flacon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parfums_personnalises', to='catalogue.flacon'),
        ),
        migrations.AddField(
            model_name='parfumpersonnaliseligne',
            name='essence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='catalogue.essence'),
        ),
        migrations.AddField(
            model_name='parfumpersonnaliseligne',
            name='parfum_personnalise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='laboratoire.parfumpersonnalise'),
        ),
        migrations.AlterUniqueTogether(
            name='parfumpersonnaliseligne',
            unique_together={('parfum_personnalise', 'essence')},
        ),
    ]
