# Generated by Django 4.2.30 on 2026-05-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
        ('laboratoire', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parfumpersonnaliseligne',
            name='essence_catalogue',
        ),
        migrations.AddField(
            model_name='parfumpersonnalise',
            name='enregistre',
            field=models.BooleanField(default=True, help_text='Détermine si le parfum est enregistré dans la collection du client.'),
        ),
        migrations.AddField(
            model_name='parfumpersonnaliseligne',
            name='essence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_parfum', to='catalogue.lotessence'),
        ),
        migrations.AlterField(
            model_name='parfumpersonnalise',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
