# Generated by Django 6.0.4 on 2026-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parfumpersonnaliseligne',
            name='prix_ligne',
            field=models.DecimalField(decimal_places=2, help_text='prix_par_ml_snapshot * quantite_ml', max_digits=10),
        ),
        migrations.AlterField(
            model_name='parfumpersonnaliseligne',
            name='prix_par_ml_snapshot',
            field=models.DecimalField(decimal_places=2, help_text="Prix de l'essence au ml au moment de la création", max_digits=10),
        ),
    ]
