# Generated by Django 6.0.4 on 2026-05-12 20:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_ingredient_essence_categorie'),
        ('laboratoire', '0003_alter_parfumpersonnaliseligne_prix_ligne_and_more'),
        ('utilisateur', '0004_commissionlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parfumpersonnaliseligne',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parfumpersonnaliseligne',
            name='essence_catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_parfum', to='catalogue.essence'),
        ),
        migrations.CreateModel(
            name='EssencePersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom donné par le client à son essence', max_length=200)),
                ('prix_par_ml_calcule', models.DecimalField(decimal_places=2, default=0, help_text='Prix calculé en fonction des ingrédients', max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essences_personnalisees', to='utilisateur.client')),
            ],
            options={
                'verbose_name': 'Essence Personnalisée',
                'verbose_name_plural': 'Essences Personnalisées',
                'db_table': 'essence_personnalisee',
            },
        ),
        migrations.AddField(
            model_name='parfumpersonnaliseligne',
            name='essence_personnalisee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_parfum', to='laboratoire.essencepersonnalisee'),
        ),
        migrations.RemoveField(
            model_name='parfumpersonnaliseligne',
            name='essence',
        ),
        migrations.CreateModel(
            name='EssencePersonnaliseeLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ml', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('prix_par_ml_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ligne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('essence_personnalisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='laboratoire.essencepersonnalisee')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='catalogue.ingredient')),
            ],
            options={
                'verbose_name': "Ligne d'essence personnalisée",
                'verbose_name_plural': "Lignes d'essences personnalisées",
                'db_table': 'essence_personnalisee_ligne',
                'unique_together': {('essence_personnalisee', 'ingredient')},
            },
        ),
    ]
