# Generated by Django 6.0.4 on 2026-05-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0004_alter_parfumpersonnaliseligne_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parfumpersonnalise',
            name='contenance_ml',
        ),
    ]
