import type { Product } from '@/types';

export const mockAccessories: Product[] = [
  {
    id: 'acc-001',
    name: 'Montre Royale Or',
    description: 'Montre chronographe plaqué or 18 carats. Bracelet cuir italien.',
    price: 185000,
    category: 'accessory',
    subCategory: 'watches',
    images: ['/images/products/watch-gold.jpg'],
    brand: 'Exclusif Collection',
    inStock: true,
    rating: 4.8,
    reviews: 24,
    isFeatured: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'acc-002',
    name: 'Montre Classique Argent',
    description: 'Cadran nacré et bracelet mesh en acier. Classique et moderne.',
    price: 125000,
    category: 'accessory',
    subCategory: 'watches',
    images: ['/images/products/watch-silver.jpg'],
    brand: 'Exclusif Collection',
    inStock: true,
    rating: 4.6,
    reviews: 18,
    isFeatured: false,
    createdAt: '2026-01-20',
  },
  {
    id: 'acc-003',
    name: 'Collier Perles d\'Afrique',
    description: 'Perles naturelles africaines et détails en or. Pièce unique.',
    price: 95000,
    category: 'accessory',
    subCategory: 'jewelry',
    images: ['/images/products/necklace-pearls.jpg'],
    brand: 'Numba Accessories',
    inStock: true,
    rating: 4.9,
    reviews: 32,
    isFeatured: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'acc-004',
    name: 'Bracelet Cuir Tressé',
    description: 'Cuir tressé main avec fermoir magnétique en acier.',
    price: 35000,
    category: 'accessory',
    subCategory: 'jewelry',
    images: ['/images/products/bracelet-leather.jpg'],
    brand: 'Exclusif Collection',
    inStock: true,
    rating: 4.5,
    reviews: 45,
    isFeatured: false,
    createdAt: '2026-02-10',
  },
  {
    id: 'acc-005',
    name: 'Lunettes Aviator Gold',
    description: 'Monture dorée et verres polarisés dégradés. UV400.',
    price: 75000,
    category: 'accessory',
    subCategory: 'sunglasses',
    images: ['/images/products/sunglasses-aviator.jpg'],
    brand: 'Exclusif Vision',
    inStock: true,
    rating: 4.7,
    reviews: 19,
    isFeatured: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'acc-006',
    name: 'Sac Bandoulière Élite',
    description: 'Cuir synthétique premium avec finitions dorées.',
    price: 65000,
    category: 'accessory',
    subCategory: 'bags',
    images: ['/images/products/bag-crossbody.jpg'],
    brand: 'Exclusif Collection',
    inStock: true,
    rating: 4.4,
    reviews: 12,
    isFeatured: false,
    createdAt: '2026-03-01',
  },
  {
    id: 'acc-007',
    name: 'Ceinture Premium Noir',
    description: 'Cuir véritable, boucle acier poli. Réversible noir/marron.',
    price: 45000,
    category: 'accessory',
    subCategory: 'belts',
    images: ['/images/products/belt-black.jpg'],
    brand: 'Exclusif Collection',
    inStock: true,
    rating: 4.6,
    reviews: 28,
    isFeatured: false,
    createdAt: '2026-03-05',
  },
  {
    id: 'acc-008',
    name: 'Bague Signature Or Rose',
    description: 'Or rose avec pierre centrale en zircone. Design minimaliste.',
    price: 55000,
    category: 'accessory',
    subCategory: 'jewelry',
    images: ['/images/products/ring-rosegold.jpg'],
    brand: 'Numba Accessories',
    inStock: true,
    rating: 4.8,
    reviews: 15,
    isFeatured: true,
    createdAt: '2026-03-10',
  },
];

export const mockPerfumes: Product[] = [
  {
    id: 'prf-001',
    name: 'Sauvage Elixir',
    description: 'Intense et mystérieux. Lavande, réglisse et santal.',
    price: 95000,
    category: 'perfume-brand',
    images: ['/images/products/perfume-sauvage.jpg'],
    brand: 'Dior',
    inStock: true,
    rating: 4.9,
    reviews: 156,
    notes: { top: ['Bergamote', 'Pamplemousse'], middle: ['Lavande', 'Réglisse'], base: ['Santal', 'Ambre'] },
    volume: '100ml',
    isFeatured: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'prf-002',
    name: 'Bleu de Chanel',
    description: 'Liberté masculine. Boisé aromatique vibrant.',
    price: 85000,
    category: 'perfume-brand',
    images: ['/images/products/perfume-bleu.jpg'],
    brand: 'Chanel',
    inStock: true,
    rating: 4.8,
    reviews: 203,
    notes: { top: ['Citron', 'Menthe'], middle: ['Gingembre', 'Jasmin'], base: ['Cèdre', 'Santal'] },
    volume: '100ml',
    isFeatured: true,
    createdAt: '2026-01-05',
  },
  {
    id: 'prf-003',
    name: 'La Nuit de l\'Homme',
    description: 'Séduction nocturne. Cardamome, lavande et cèdre.',
    price: 78000,
    category: 'perfume-brand',
    images: ['/images/products/perfume-nuit.jpg'],
    brand: 'Yves Saint Laurent',
    inStock: true,
    rating: 4.7,
    reviews: 89,
    notes: { top: ['Cardamome', 'Bergamote'], middle: ['Lavande', 'Cèdre'], base: ['Vétiver', 'Coumarine'] },
    volume: '100ml',
    isFeatured: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'prf-004',
    name: 'Acqua di Gio Profondo',
    description: 'La profondeur de l\'océan. Aquatique boisé raffiné.',
    price: 82000,
    category: 'perfume-brand',
    images: ['/images/products/perfume-acqua.jpg'],
    brand: 'Giorgio Armani',
    inStock: true,
    rating: 4.6,
    reviews: 134,
    notes: { top: ['Bergamote', 'Mandarine'], middle: ['Cyprès', 'Lavande'], base: ['Musc', 'Ambre'] },
    volume: '75ml',
    isFeatured: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'dupe-001',
    name: 'Sauvage Intense (Dupe)',
    description: 'Notre interprétation du Sauvage. Même puissance, prix accessible.',
    price: 15000,
    category: 'perfume-dupe',
    images: ['/images/products/dupe-sauvage.jpg'],
    brand: 'Exclusif Parfums',
    originalBrand: 'Dior - Sauvage',
    inStock: true,
    rating: 4.5,
    reviews: 67,
    notes: { top: ['Bergamote', 'Poivre'], middle: ['Lavande', 'Géranium'], base: ['Ambre', 'Cèdre'] },
    volume: '50ml',
    isFeatured: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'dupe-002',
    name: 'Bleu Intense (Dupe)',
    description: 'Inspiré du Bleu de Chanel. Fraîcheur boisée accessible.',
    price: 12000,
    category: 'perfume-dupe',
    images: ['/images/products/dupe-bleu.jpg'],
    brand: 'Exclusif Parfums',
    originalBrand: 'Chanel - Bleu',
    inStock: true,
    rating: 4.3,
    reviews: 45,
    notes: { top: ['Citron', 'Menthe'], middle: ['Gingembre', 'Cèdre'], base: ['Santal', 'Musc'] },
    volume: '50ml',
    isFeatured: false,
    createdAt: '2026-02-05',
  },
  {
    id: 'dupe-003',
    name: 'Nuit Séduction (Dupe)',
    description: 'Version accessible de La Nuit de l\'Homme YSL.',
    price: 13000,
    category: 'perfume-dupe',
    images: ['/images/products/dupe-nuit.jpg'],
    brand: 'Exclusif Parfums',
    originalBrand: 'YSL - La Nuit de l\'Homme',
    inStock: true,
    rating: 4.4,
    reviews: 38,
    notes: { top: ['Cardamome'], middle: ['Lavande', 'Cèdre'], base: ['Vétiver', 'Coumarine'] },
    volume: '50ml',
    isFeatured: false,
    createdAt: '2026-02-10',
  },
  {
    id: 'numba-001',
    name: 'Numba N°1 — Roi du Sahel',
    description: 'Oriental boisé puissant inspiré des nuits sahéliennes.',
    price: 35000,
    category: 'numba-creation',
    images: ['/images/products/numba-sahel.jpg'],
    brand: 'Numba',
    inStock: true,
    rating: 4.9,
    reviews: 52,
    notes: { top: ['Cardamome', 'Bergamote'], middle: ['Encens', 'Rose'], base: ['Oud', 'Ambre', 'Santal'] },
    volume: '100ml',
    isFeatured: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'numba-002',
    name: 'Numba N°2 — Fleur de Douala',
    description: 'Hommage floral à Douala. Jasmin et bois précieux.',
    price: 30000,
    category: 'numba-creation',
    images: ['/images/products/numba-douala.jpg'],
    brand: 'Numba',
    inStock: true,
    rating: 4.7,
    reviews: 34,
    notes: { top: ['Mandarine', 'Pêche'], middle: ['Jasmin', 'Ylang-Ylang'], base: ['Patchouli', 'Vanille'] },
    volume: '100ml',
    isFeatured: true,
    createdAt: '2026-03-15',
  },
  {
    id: 'numba-003',
    name: 'Numba N°3 — Minuit Africain',
    description: 'Oriental gourmand mystérieux. Cacao, épices et bois rares.',
    price: 38000,
    category: 'numba-creation',
    images: ['/images/products/numba-minuit.jpg'],
    brand: 'Numba',
    inStock: true,
    rating: 4.8,
    reviews: 41,
    notes: { top: ['Poivre noir', 'Bergamote'], middle: ['Cacao', 'Cannelle'], base: ['Oud', 'Musc', 'Vanille'] },
    volume: '100ml',
    isFeatured: false,
    createdAt: '2026-04-01',
  },
];

export const allProducts: Product[] = [...mockAccessories, ...mockPerfumes];
