# Generated by Django 6.0.4 on 2026-05-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestataire',
            name='email_professionnel',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='entreprise',
        ),
    ]
