# Generated by Django 6.0.4 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_remove_prestataire_email_professionnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='code_promo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('inactif', 'Inactif')], default='en_attente', max_length=20),
        ),
    ]
