# Generated by Django 6.0.4 on 2026-05-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_prestataire_code_promo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('vente', 'Commission sur vente'), ('retrait', 'Retrait de solde'), ('bonus', 'Bonus / Ajustement')], default='vente', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_commande', models.CharField(blank=True, max_length=50, null=True)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_commissions', to='utilisateur.prestataire')),
            ],
            options={
                'db_table': 'commission_log',
                'ordering': ['-date_operation'],
            },
        ),
    ]
