# Generated by Django 6.0.4 on 2026-05-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_global_admin',
            field=models.BooleanField(default=False),
        ),
    ]
