# Generated by Django 6.0.4 on 2026-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_notification_is_global_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='reduction_client_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
