# Generated by Django 6.0.4 on 2026-05-21 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_prestataire_reduction_client_pourcentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telephone_destination', models.CharField(max_length=20)),
                ('reference_unique', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_cours', max_length=20)),
                ('motif_echec', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_finalisation', models.DateTimeField(blank=True, null=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='utilisateur.prestataire')),
            ],
            options={
                'db_table': 'payout_transaction',
                'ordering': ['-date_creation'],
            },
        ),
    ]
