# Generated by Django 6.0.4 on 2026-05-02 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieparfum',
            name='taux_reduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction en % appliquée à tous les parfums de cette catégorie (0 = pas de réduction)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='typeaccessoire',
            name='taux_reduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction en % appliquée à tous les accessoires de ce type (0 = pas de réduction)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='typeflacon',
            name='taux_reduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction en % appliquée à tous les flacons de ce type (0 = pas de réduction)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='categorieparfum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parfums/'),
        ),
    ]
