# Generated by Django 4.2.30 on 2026-05-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='utilisateur.client'),
        ),
        migrations.AddField(
            model_name='favori',
            name='parfum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.parfum'),
        ),
        migrations.AddField(
            model_name='essence',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='essences', through='catalogue.TagEssence', to='catalogue.tag'),
        ),
        migrations.AddField(
            model_name='accessoire',
            name='type_accessoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessoires', to='catalogue.typeaccessoire'),
        ),
        migrations.AlterUniqueTogether(
            name='tagparfum',
            unique_together={('parfum', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='tagessence',
            unique_together={('essence', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='produitfiniessence',
            unique_together={('essence', 'taille_ml')},
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(condition=models.Q(('parfum__isnull', False)), fields=('client', 'parfum'), name='unique_favori_parfum'),
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(condition=models.Q(('accessoire__isnull', False)), fields=('client', 'accessoire'), name='unique_favori_accessoire'),
        ),
        migrations.AlterUniqueTogether(
            name='essence',
            unique_together={('marque', 'nom', 'categorie')},
        ),
    ]
