# Generated by Django 4.2.30 on 2026-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotessence',
            options={'ordering': ['date_reception'], 'verbose_name': "Lot d'essence (labo)", 'verbose_name_plural': "Lots d'essence (labo)"},
        ),
        migrations.AddField(
            model_name='essence',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='flacon',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='typeflacon',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accessoire',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='categorieparfum',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='essence',
            name='description_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='essence',
            name='marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parfum',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='typeaccessoire',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
