# Generated by Django 6.0.4 on 2026-05-03 01:44

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_categorieparfum_taux_reduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essence',
            name='image_principale',
            field=models.ImageField(blank=True, help_text="Image de l'essence (flacon fournisseur, matière première)", null=True, upload_to=catalogue.models.upload_to_essence),
        ),
        migrations.AlterField(
            model_name='accessoire',
            name='image_principale',
            field=models.ImageField(blank=True, help_text="Image principale de l'accessoire", null=True, upload_to=catalogue.models.upload_to_accessoire),
        ),
        migrations.AlterField(
            model_name='categorieparfum',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de la catégorie (jpg, png, webp)', null=True, upload_to=catalogue.models.upload_to_categorie),
        ),
        migrations.AlterField(
            model_name='flacon',
            name='image_principale',
            field=models.ImageField(blank=True, help_text='Image principale du flacon', null=True, upload_to=catalogue.models.upload_to_flacon),
        ),
        migrations.AlterField(
            model_name='parfum',
            name='image_principale',
            field=models.ImageField(blank=True, help_text='Image principale du parfum (jpg, png, webp — max 2Mo)', null=True, upload_to=catalogue.models.upload_to_parfum),
        ),
        migrations.AlterField(
            model_name='parfum',
            name='images_supplementaires',
            field=models.JSONField(blank=True, default=list, help_text="URLs des images supplémentaires (géré via l'upload multiple)"),
        ),
        migrations.AlterField(
            model_name='typeaccessoire',
            name='icone',
            field=models.ImageField(blank=True, help_text="Icône du type d'accessoire (svg, png — fond transparent recommandé)", null=True, upload_to=catalogue.models.upload_to_type_accessoire),
        ),
        migrations.AlterField(
            model_name='typeflacon',
            name='image',
            field=models.ImageField(blank=True, help_text='Image représentative du type de flacon', null=True, upload_to=catalogue.models.upload_to_type_flacon),
        ),
    ]
