# Generated by Django 4.2.30 on 2026-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_lotessence_options_essence_slug_flacon_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotessence',
            name='stock_precedent_ml',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Stock total de l'essence avant cet ajout", max_digits=12),
        ),
        migrations.AddField(
            model_name='produitfiniessence',
            name='stock_precedent',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Stock de ce format avant la mise à jour'),
        ),
    ]
