# Generated by Django 6.0.4 on 2026-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_essence_image_principale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoire',
            name='est_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessoire',
            name='est_hotseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parfum',
            name='est_hotseller',
            field=models.BooleanField(default=False),
        ),
    ]
