# Generated by Django 6.0.4 on 2026-05-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_accessoire_est_bestseller_accessoire_est_hotseller_and_more'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoire',
            name='marque',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='essence',
            name='couleur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='essence',
            name='duree',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='essence',
            name='marque',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parfum',
            name='duree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parfum',
            name='marque',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('accessoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.accessoire')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='utilisateur.client')),
                ('parfum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.parfum')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'favori',
                'constraints': [models.UniqueConstraint(condition=models.Q(('parfum__isnull', False)), fields=('client', 'parfum'), name='unique_favori_parfum'), models.UniqueConstraint(condition=models.Q(('accessoire__isnull', False)), fields=('client', 'accessoire'), name='unique_favori_accessoire')],
            },
        ),
    ]
