# Generated by Django 6.0.4 on 2026-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_accessoire_marque_essence_couleur_essence_duree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essence',
            name='image_principale',
        ),
        migrations.AddField(
            model_name='essence',
            name='notes_coeur',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='essence',
            name='notes_fond',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='essence',
            name='notes_tete',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
