# Generated by Django 6.0.4 on 2026-05-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_rename_essence_prix_par_ml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('note_olfactive', models.CharField(choices=[('tête', 'Tête'), ('coeur', 'Cœur'), ('fond', 'Fond')], max_length=20)),
                ('prix_par_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_ml', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'db_table': 'ingredient',
            },
        ),
        migrations.AddField(
            model_name='essence',
            name='categorie',
            field=models.CharField(choices=[('super_premium', 'Super Premium'), ('premium', 'Premium'), ('high', 'High')], default='premium', max_length=20),
        ),
    ]
