# Generated by Django 6.0.4 on 2026-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_ingredient_essence_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essence',
            options={'ordering': ['nom'], 'verbose_name': 'Essence', 'verbose_name_plural': 'Essences'},
        ),
        migrations.RemoveField(
            model_name='essence',
            name='stock_litre',
        ),
        migrations.AddField(
            model_name='essence',
            name='contenance_ml',
            field=models.PositiveIntegerField(default=10, help_text="Contenance d'un flacon (ex: 10 pour 10ml)"),
        ),
        migrations.AddField(
            model_name='essence',
            name='prix_unitaire_fini',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix du flacon'),
        ),
        migrations.AddField(
            model_name='essence',
            name='stock_flacon',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de flacons neufs'),
        ),
        migrations.AddField(
            model_name='essence',
            name='stock_ml_total_reel',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='essence',
            name='stock_ouvert_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reliquat Labo (ml ouverts)'),
        ),
        migrations.AddField(
            model_name='essence',
            name='vendu_comme_produit_fini',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='essence',
            name='couleur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='essence',
            name='duree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='essence',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='essence',
            name='prix_par_ml',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
