# Generated by Django 6.0.4 on 2026-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_ingredient_note_olfactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='note_olfactive',
            field=models.CharField(blank=True, choices=[('tête', 'Tête'), ('coeur', 'Cœur'), ('fond', 'Fond')], max_length=20, null=True),
        ),
    ]
