# Generated by Django 4.2.30 on 2026-05-28 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratoire', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('assignée', 'Assignée'), ('livrée', 'Livrée'), ('échouée', 'Échouée')], default='assignée', max_length=30)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('frais_livraison', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motif_echec', models.TextField(blank=True)),
                ('note_admin', models.TextField(blank=True)),
                ('note_livreur', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affectation de livraison',
                'verbose_name_plural': 'Affectations de livraisons',
                'db_table': 'affectation_livraison',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('livrée', 'Livrée'), ('annulée', 'Annulée'), ('remboursée', 'Remboursée')], default='en_attente', max_length=30)),
                ('statut_livraison', models.CharField(blank=True, choices=[('en_attente_affectation', 'En attente affectation'), ('assignée', 'Assignée'), ('livrée', 'Livrée'), ('échouée', 'Échouée')], max_length=30, null=True)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_code_promo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('code_promo_utilise', models.CharField(blank=True, max_length=50)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_statut', models.CharField(choices=[('non_versée', 'Non versée'), ('versée', 'Versée'), ('annulée', 'Annulée')], default='non_versée', max_length=20)),
                ('livraison_nom_complet', models.CharField(max_length=200)),
                ('livraison_quartier', models.CharField(blank=True, max_length=200)),
                ('livraison_ville', models.CharField(blank=True, max_length=100)),
                ('livraison_telephone', models.CharField(max_length=20)),
                ('methode_paiement', models.CharField(choices=[('cash', 'cash'), ('mobile_money', 'mobile_money')], max_length=50)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('payé', 'Payé'), ('échoué', 'Échoué'), ('remboursé', 'Remboursé')], default='en_attente', max_length=20)),
                ('date_livraison_estimee', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('note_client', models.TextField(blank=True)),
                ('note_interne', models.TextField(blank=True)),
                ('motif_echec_livraison', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='CommandeLigneAccessoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_snapshot', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mouvement_stock_genere', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'commande_ligne_accessoire',
            },
        ),
        migrations.CreateModel(
            name='CommandeLigneParfum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_snapshot', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mouvement_stock_genere', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'commande_ligne_parfum',
            },
        ),
        migrations.CreateModel(
            name='CommandeLigneParfumPerso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_laboratoire', models.CharField(choices=[('en_attente', 'En attente'), ('validée', 'Validée'), ('livrée', 'Livrée')], default='en_attente', max_length=30)),
                ('proportions_mises_a_jour', models.BooleanField(default=False, help_text='True quand stock essence et flacon décrémentés')),
                ('note_laboratoire', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'commande_ligne_parfum_perso',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_promo_applique', models.CharField(blank=True, max_length=50)),
                ('remise_montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remise_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('converti', 'Converti')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'db_table': 'panier',
            },
        ),
        migrations.CreateModel(
            name='PanierLigneParfumPerso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_calcule', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note_client', models.TextField(blank=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_parfums_perso', to='orders.panier')),
                ('parfum_personnalise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.parfumpersonnalise')),
            ],
            options={
                'db_table': 'panier_ligne_parfum_perso',
            },
        ),
        migrations.CreateModel(
            name='PanierLigneParfum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_parfums', to='orders.panier')),
                ('parfum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.parfum')),
            ],
            options={
                'db_table': 'panier_ligne_parfum',
            },
        ),
        migrations.CreateModel(
            name='PanierLigneAccessoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.accessoire')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_accessoires', to='orders.panier')),
            ],
            options={
                'db_table': 'panier_ligne_accessoire',
            },
        ),
    ]
