# Generated by Django 6.0.4 on 2026-04-30 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('laboratoire', '0002_initial'),
        ('orders', '0001_initial'),
        ('utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationlivraison',
            name='affecte_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_faites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectationlivraison',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='utilisateur.livreur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='utilisateur.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='utilisateur.livreur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='utilisateur.prestataire'),
        ),
        migrations.AddField(
            model_name='affectationlivraison',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='commandeligneaccessoire',
            name='accessoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_lignes', to='catalogue.accessoire'),
        ),
        migrations.AddField(
            model_name='commandeligneaccessoire',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_accessoires', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='commandeligneparfum',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_parfums', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='commandeligneparfum',
            name='parfum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_lignes', to='catalogue.parfum'),
        ),
        migrations.AddField(
            model_name='commandeligneparfumperso',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_parfums_perso', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='commandeligneparfumperso',
            name='parfum_personnalise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_lignes', to='laboratoire.parfumpersonnalise'),
        ),
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='utilisateur.client'),
        ),
        migrations.AddField(
            model_name='panier',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='utilisateur.prestataire'),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_associee', to='orders.panier'),
        ),
        migrations.AddField(
            model_name='panierligneaccessoire',
            name='accessoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.accessoire'),
        ),
        migrations.AddField(
            model_name='panierligneaccessoire',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_accessoires', to='orders.panier'),
        ),
        migrations.AddField(
            model_name='panierligneparfum',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_parfums', to='orders.panier'),
        ),
        migrations.AddField(
            model_name='panierligneparfum',
            name='parfum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.parfum'),
        ),
        migrations.AddField(
            model_name='panierligneparfumperso',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_parfums_perso', to='orders.panier'),
        ),
        migrations.AddField(
            model_name='panierligneparfumperso',
            name='parfum_personnalise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.parfumpersonnalise'),
        ),
    ]
