# Generated by Django 6.0.4 on 2026-05-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='motif_echec_livraison',
            field=models.TextField(blank=True, null=True),
        ),
    ]
